---
- name: install nginx package
  pkgng:
    name: nginx
    state: present

# this seems to be needed, but not formally required, for nginx
- name: install pcre package
  pkgng:
    name: pcre
    state: present

- name: make sure necessary configuration directories exist
  file:
    path: "{{ nginx_conf_dir }}/{{item}}"
    mode: "0755"
    state: directory
  with_items:
  - conf.d
  - sites

- name: make sure log directory exists
  file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  with_items:
  - "{{ nginx_log_dir }}"
  - "{{ nginx_log_dir }}/{{ server_name }}"

- name: make sure spool exists
  file:
    path: "{{ nginx_spool_dir }}"
    mode: "0755"
    state: directory
    owner: "www"
    group: "www"

- name: install server configuration file
  template:
    src: "{{ nginx_template }}"
    dest: "{{ nginx_conf_dir }}/sites/{{ server_name }}"
  notify: reload nginx

- name: create ssl certificate directory
  file:
    path: "{{ nginx_cert_dir }}"
    state: directory
    mode: 0600
    owner: root
    group: wheel
  when: ssl

- name: create ssl cert file
  copy:
    content: "{{ ssl_keys[server_name]['cert'] }}"
    dest: "{{ nginx_cert_dir }}/{{ server_name }}.crt"
  when: ssl

- name: create ssl key file
  copy:
    content: "{{ ssl_keys[server_name]['key'] }}"
    dest: "{{ nginx_cert_dir }}/{{ server_name }}.key"
    mode: 0600
    owner: root
    group: wheel
  when: ssl

- name: create DHE parameter file
  command: "/usr/bin/openssl dhparam -out {{ nginx_conf_dir }}/dhparam.pem 2048"
  args:
    creates: "{{ nginx_conf_dir }}/dhparam.pem"

- name: set permissions on DHE parameter file
  file:
    path: "{{ nginx_conf_dir }}/dhparam.pem"
    mode: 0600
    owner: root
    group: wheel

- name: install nginx.conf
  template:
    src: "nginx.conf"
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify: reload nginx

- name: install ssl configuration file
  template:
    src: "ssl.conf"
    dest: "{{ nginx_conf_dir }}/conf.d/ssl.conf"
  notify: reload nginx

- name: enable and start nginx service
  service:
    name: nginx
    enabled: true
    state: running
