---
- name: install nginx package
  pkgng:
    name: nginx
    state: present

- name: make sure necessary directories exist
  file:
    path: "{{ nginx_conf_dir }}/{{item}}"
    mode: "0755"
    state: directory
  with_items:
  - conf.d
  - sites-available     # XXX(sa2ajj): I am not sure about this item in our setup
  - sites-enabled

- name: make sure log directory exists
  file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  with_items:
  - "{{ nginx_log_dir }}"
  - "{{ nginx_log_dir }}/{{ server_name }}"

- name: install server configuration file
  template:
    src: "{{ nginx_template }}"
    dest: "{{ nginx_conf_dir }}/sites-enabled/{{ server_name }}"
  notify: reload nginx

- name: install nginx.conf
  template:
    src: "nginx.conf"
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify: reload nginx

- name: enable and start nginx service
  service:
    name: nginx
    enabled: true
    state: running
