---
- name: install nginx package
  pkgng:
    name: nginx
    state: present

- name: make sure necessary directories exist
  file:
    path: "{{ nginx_conf_dir }}/{{item}}"
    mode: "0755"
    state: directory
  with_items:
  - conf.d
  - sites-available
  - sites-enabled

- name: make sure log directory exists
  file:
    path: "{{ nginx_log_dir }}"
    mode: "0755"
    state: directory

- name: install nginx.conf
  template:
    src: "nginx.conf"
    dest: "{{ nginx_conf_dir }}/nginx.conf"
  notify: reload nginx

- name: enable and start nginx service
  service:
    name: nginx
    enabled: true
    state: running
