- name: Install uwsgi
  pkgng:
    name: uwsgi
    state: present

- name: Make uwsgi etc directory
  file:
    path: /usr/local/etc/uwsgi
    state: directory

- name: Configure uwsgi for trac
  copy:
    src: uwsgi.ini
    dest: /usr/local/etc/uwsgi/uwsgi.ini
  notify: reload uwsgi

- name: Set uwsgi process permissions
  lineinfile:
    dest: "/etc/rc.conf"
    line: "{{item.option}}=\"{{item.value}}\""
    regexp: "^{{item.option}}=.*"
    state: present
  with_items:
    # This maps to www:www.
    - option: uwsgi_uid
      value: 80
    - option: uwsgi_gid
      value: 80

- name: Enable uwsgi
  service:
    name: uwsgi
    state: started
    enabled: yes
