---
- name: configure vm1
  hosts: vm1
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  # Restore once jails are moved to service{1,2,3}
  # - base-servicehost
  - role: jail
    name: www
    hostname: www.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.238'
    - 'vlan0|192.168.80.238'
  - role: jail
    name: docs
    hostname: docs.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.237'
    - 'vlan0|192.168.80.237'

# vim:ts=2:sw=2:noai:nosi
