---
- name: configure service2
  hosts: service2
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  - sendmail
  - role: jail
    name: nine
    hostname: nine.buildbot.net
    ip_address:
    - 'lagg0|140.211.10.244'
    - 'vlan0|192.168.80.244'

# vim:ts=2:sw=2:noai:nosi
