---
- name: configure service3
  hosts: service3
  gather_facts: no
  connection: local
  sudo: yes
  roles:
  - role: jail
    name: buildbot
    hostname: buildbot.buildbot.net
    ip_address:
    - 'lo0|127.0.0.239'       # localhost, must be first
    - 'lagg0|140.211.10.239'
    - 'vlan0|192.168.80.239'
  - role: jail
    name: mysql
    hostname: mysql.int.buildbot.net
    ip_address:
    - 'vlan0|192.168.80.215'
  - role: jail
    name: bslave1
    hostname: bslave1.int.buildbot.net
    ip_address:
      - 'vlan0|192.168.80.226'

# vim:ts=2:sw=2:noai:nosi
