---
- name: configure events
  hosts: events
  gather_facts: no
  connection: local
  become: yes
  vars:
    web_host_name: "events.buildbot.net"

  roles:
  - base
  - role: elk
    server_name: "{{ web_host_name }}"
