---
- name: configure syslog
  hosts: syslog
  gather_facts: no
  connection: local
  become: yes
  vars:
    web_host_name: "syslog.buildbot.net"
  roles:
    - role: elk
      logstash_variant: syslog
      server_name: "{{ web_host_name }}"
      github_team: "core"  # this restricts access to only people in the github 'core' team
