---
- hosts: all
  gather_facts: no
  tasks:
    - name: load secrets from "{{ secrets_file|default('secrets.yml') }}"
      include_vars: "{{ secrets_file|default('secrets.yml') }}"
      tags: always
