# This is a playbook to be run with ansible-pull (the usage will be described
# when a particular cron task is installed).
# To deploy a particular service manually:
# * log into the target host
# * run 'ansible-playbook -i localhost local.yml -K'
---
- include: "load-secrets.yml"

- name: determine local host name
  hosts: all
  gather_facts: yes
  connection: local

  tasks:
  # Use this to create "special" groups that will be used to setup a particular host.
  # We use non-fqdn here so a staging/test setup could work as well.
  - group_by:
      key: "{{ansible_hostname}}"
    changed_when: False

# Service hosts
- include: "host-service1.yml"
- include: "host-service2.yml"
- include: "host-service3.yml"
- include: "host-vm1.yml"

# Jails
- include: "jail-ns1.yml"
- include: "jail-nine.yml"
- include: "jail-www.yml"

# vim:ts=2:sw=2:noai:nosi
