---
- name: create the user
  user:
    name: "{{ user_id }}"
    comment: "{{ user_name }}"
    state: present

- name: add authorized keys
  authorized_key:
    user: "{{ user_id }}"
    key: "{{ authorized_key }}"
  when: authorized_key

# NOTE: the information will only be available until the next use of `getent`
- name: get user information
  getent:
    database: passwd
    key: "{{ user_id }}"
  tags: always
