---
- name: Install ezjail
  pkgng:
    name: ezjail
    state: present

- name: ezjail config
  template:
    src: ezjail.conf
    dest: /usr/local/etc/ezjail.conf

- name: Create jail log directory
  file:
    path: '{{ jail_log_dir }}'
    state: directory

- name: Populate basejail
  command: ezjail-admin install
  args:
    creates: '{{ ezjail_jaildir }}/base'

- name: Create base flavour directories
  file:
    path: '{{ ezjail_jaildir }}/flavours/base/{{ item }}'
    state: directory
  with_items:
  - etc

- name: Set base flavour config
  copy:
    dest: '{{ ezjail_jaildir }}/flavours/{{ item }}'
    src: 'flavours/{{ item }}'
  with_items:
  - base/ezjail.flavour
  - base/etc/make.conf
  - base/etc/periodic.conf
  - base/etc/rc.conf

- name: Enable jails
  service:
    name: ezjail
    enabled: true
