- name: install postfix (FreeBSD)
  pkgng:
    name: postfix
    state: present
  when: 'ansible_distribution == "FreeBSD"'
  environment: "{{ proxy_env }}"

- name: add postfix config
  notify: Reload Postfix
  copy:
    src: "{{item}}"
    dest: "/usr/local/etc/postfix/{{item}}"
  with_items:
    - main.cf
    - master.cf
    - local-host-names
    - virtusertable
    - transport
