---
dependencies:
- base

- role: packages
  packages:
    - elasticsearch2
    - logstash
    - kibana43

- role: nginx
  nginx_template: multiproxy
  upstream_urls:
      - endpoint: /kibana
        url: "{{ local_ip }}:{{ kibana_port }}"
      - endpoint: /events
        url: "{{ local_ip }}:{{ logstash_port }}"
  ssl: true
