---
- name: Install ezjail
  pkgng:
    name: ezjail

- name: ezjail config
  template:
    src: ezjail.conf
    dest: /usr/local/etc/ezjail.conf

- name: Populate basejail
  command: ezjail-admin install -p
  args:
    creates: '{{ ezjail_jaildir }}/base'

- name: Create base flavour directories
  file:
    path: '{{ ezjail_jaildir }}/flavours/base/{{ item }}'
    state: directory
  with_items:
      - etc

- name: Set base flavour config
  copy:
    dest: '{{ ezjail_jaildir }}/flavours/{{ item }}'
    src: 'flavours/{{ item }}'
  with_items:
    - base/ezjail.flavour
    - base/etc/make.conf
    - base/etc/periodic.conf
    - base/etc/rc.conf

- name: Install jail
  command: ezjail-admin create -f base {{ name }} {{ ip_address|join(',') }}
  args:
    creates: '{{ ezjail_jaildir }}/{{ name }}'

- name: Enable jails
  lineinfile:
    dest: /etc/rc.conf
    line: 'jail_enable="YES"'
    state: present
