---
- name: create jail
  command: "ezjail-admin create -f {{ ezjail_default_flavour }} {{ name }} {{ ip_address|join(',') }}"
  args:
    creates: "{{ ezjail_conf_dir }}/{{ name }}"
  register: jail_created

- name: set jail's hostname
  lineinfile:
    dest: "{{ ezjail_conf_dir }}/{{ name }}"
    regexp: "^export jail_{{ name }}_hostname="
    line: 'export jail_{{ name }}_hostname="{{ hostname }}"'
  when: jail_created|changed

- name: check if the jail is running
  shell: "jls -j {{ name }} > /dev/null 2>&1"
  ignore_errors: True
  register: jail_running

- name: start the jail
  command: "ezjail-admin start {{ name }}"
  when: jail_running|failed

# vim:ts=2:sw=2:noai:nosi
