---
dependencies:
- base
- role: nginx
  nginx_template: static
  server_name: "{{ ftp_hostname }}"
  server_root: "{{ ftp_root }}"
  extra_config_from: "roles/ftp/files/ftp-nginx.conf"
- role: vsftp
  server_name: "{{ ftp_hostname }}"
  server_root: "{{ ftp_root }}"
