---
- name: install ansible
  pkgng:
    name: ansible
    state: present

- name: create service account
  user:
    name: "{{ service_account }}"
    groups: wheel
    home: "/home/{{ service_account }}"
    state: present

- name: install vault password
  copy:
    content: "{{ vault_password }}"
    dest: "/home/{{ service_account }}/.vault-password"
    mode: 0600
    owner: "{{ service_account }}"
    group: wheel

# ansible-pull expects the inventory file to exist already, even before it
# clones the repo, so we clone the repo explicitly.
- name: clone ansible git repository
  sudo_user: "{{ service_account }}"
  git:
    repo: "{{ ansible_git_repository }}"
    dest: "/home/{{ service_account }}/repo"
    version: master
    accept_hostkey: yes

- name: install ansible-pull crontask
  tags: ansible-pull
  cron:
    name: ansible-pull
    job: "ansible-pull -C master -d /home/{{ service_account }}/repo/ -m git -U {{ ansible_git_repository }} -o -s 3600 -i localhost --vault-password-file=/home/{{ service_account }}/.vault-password local.yml"
    user: "{{ service_account }}"
    minute: 0
    state: "{{ 'absent' if no_ansible_pull|default('false')|bool else 'present' }}"

# vim:ft=yaml:nosi:noai:ts=2:sw=2
