---
- name: install ansible
  pkgng:
    name: ansible
    state: present

- name: create service account
  user:
    name: "{{ service_account }}"
    groups: wheel
    state: present

- name: create /var/ansible
  file:
    path: /var/ansible
    mode: 0700
    owner: "{{ service_account }}"
    group: wheel
    state: directory

- name: install vault password
  copy:
    content: "{{ vault_password }}"
    dest: /var/ansible/.vault-password
    mode: 0600
    owner: "{{ service_account }}"
    group: wheel

# ansible-pull expects the inventory file to exist already, even before it
# clones the repo, so we clone the repo explicitly.
- name: clone ansible git repository
  sudo_user: "{{ service_account }}"
  git:
    repo: "{{ ansible_git_repository }}"
    dest: /var/ansible/repo
    accept_hostkey: yes

- name: install ansible-pull crontask
  tags: ansible-pull
  cron:
    name: ansible-pull
    job: "ansible-pull -C master -d /var/ansible/repo/ -m git -U {{ ansible_git_repository }} -o -s 3600 -i /var/ansible/repo/prod-hosts --vault-password-file=/var/ansible/.vault-password site.yml"
    user: "{{ service_account }}"
    minute: 0
    state: "{{ 'absent' if no_ansible_pull|default('false')|bool else 'present' }}"

# vim:ft=yaml:nosi:noai:ts=2:sw=2
