---
- name: enable sudo modular configuration
  lineinfile:
    dest: "{{ sudoers_root }}/sudoers"
    line: "#includedir {{ sudoers_root }}/sudoers.d"
    state: present
    validate: "visudo -cf %s"

- name: enable passwordless sudo for members of the wheel group
  copy:
    src: "sudoers-wheel"
    dest: "{{ sudoers_root }}/sudoers.d/sudoers-wheel"
