- include_tasks: rh6.yml
  when: ansible_distribution_major_version|int == 6

- include_tasks: rh7.yml
  when: ansible_distribution_major_version|int == 7

- name: "Change docker options"
  lineinfile: >
    line='other_args={{ docker_opts }}'
    regexp='^other_args='
    dest=/etc/sysconfig/docker
    state=present
